import type { Metadata } from 'next';
import { LegalPage } from '@/components/legal-page';

export const metadata: Metadata = { title: 'Terms of Service' };

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="October 2026">
      <p>
        This is a starter agreement for Runon AI. Have it reviewed by a qualified lawyer and update it to match your
        business before you launch publicly.
      </p>
      <h2>Using Runon AI</h2>
      <p>
        You may use Runon AI only in compliance with applicable law. You are responsible for the prompts you submit and
        for how you use the results.
      </p>
      <h2>AI output</h2>
      <p>
        Agent output is generated by AI and can be inaccurate or incomplete. Review it before relying on it, especially
        for legal, medical or financial decisions.
      </p>
      <h2>Acceptable use</h2>
      <ul>
        <li>Do not use the service to create malware, to harass others, or to break the law.</li>
        <li>Do not attempt to disrupt the service or access other users&apos; data.</li>
      </ul>
      <h2>Availability</h2>
      <p>The service is provided as is. We may change or discontinue features at any time.</p>
      <h2>Contact</h2>
      <p>Add your support email address here.</p>
    </LegalPage>
  );
}
